version: '3.3'
services:

  db:
    image: postgres:13.0-alpine
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env

  backend:
    build:
      context: ../manager
      dockerfile: Dockerfile
    restart: always
    volumes:
      - static_value:/app/static/
      - media_value:/app/media/
    depends_on:
      - db
    environment:
      - DEBUG=1
    env_file:
      - ./.env

  nginx:
    image: nginx:1.19.3
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx_develop.conf:/etc/nginx/conf.d/default.conf
      - static_value:/static/
      - media_value:/media/
    depends_on:
      - backend


volumes:
  static_value:
  media_value:
  postgres_data:
